/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gamepoo;

import Pieces.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Xablau
 */
public class TabuleiroRandom1 extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    final JButton[] buttonArrayEnemy = new JButton[10];
    final JButton[] buttonArrayEnemyPC = new JButton[10];

    public TabuleiroRandom1() {
        initComponents();
        setButtonsToMatrix();
        buttonArrayEnemy[0] = Button1Blue;
        buttonArrayEnemy[1] = Button2Blue;
        buttonArrayEnemy[2] = Button3Blue;
        buttonArrayEnemy[3] = Button4Blue;
        buttonArrayEnemy[4] = Button5Blue;
        buttonArrayEnemy[5] = Button6Blue;
        buttonArrayEnemy[6] = Button7Blue;
        buttonArrayEnemy[7] = Button8Blue;
        buttonArrayEnemy[8] = Button9Blue;
        buttonArrayEnemy[9] = Button10Blue;
        
        buttonArrayEnemyPC[0] = Button15Red;
        buttonArrayEnemyPC[1] = Button16Red;
        buttonArrayEnemyPC[2] = Button17Red;
        buttonArrayEnemyPC[3] = Button18Red;
        buttonArrayEnemyPC[4] = Button19Red;
        buttonArrayEnemyPC[5] = Button20Red;
        buttonArrayEnemyPC[6] = Button21Red;
        buttonArrayEnemyPC[7] = Button22Red;
        buttonArrayEnemyPC[8] = Button23Red;
        buttonArrayEnemyPC[9] = Button24Red;
    }

    private final Peças bandeira = new Bandeira();
    private final Peças bomba1 = new Bomba();
    private final Peças bomba2 = new Bomba();
    private final Peças espiao = new Espião();
    private final Peças soldado1 = new Soldado();
    private final Peças soldado2 = new Soldado();
    private final Peças soldado3 = new Soldado();
    private final Peças armeiro1 = new Armeiro();
    private final Peças armeiro2 = new Armeiro();
    private final Peças marechal = new Marechal();
    private final JButton[][] botaoMatrix = new JButton[5][5];

    RandomPlacement random = new RandomPlacement();
    ButtManager manager = new ButtManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // + 110 X ------------ + 104 Y
    private void setButtonsToMatrix() {
        botaoMatrix[0][0] = Button1Blue;
        botaoMatrix[0][1] = Button2Blue;
        botaoMatrix[0][2] = Button3Blue;
        botaoMatrix[0][3] = Button4Blue;
        botaoMatrix[0][4] = Button5Blue;
        botaoMatrix[1][0] = Button6Blue;
        botaoMatrix[1][1] = Button7Blue;
        botaoMatrix[1][2] = Button8Blue;
        botaoMatrix[1][3] = Button9Blue;
        botaoMatrix[1][4] = Button10Blue;
        botaoMatrix[2][0] = Button11White;
        botaoMatrix[2][1] = Button12White;
        botaoMatrix[2][2] = Button13White;
        botaoMatrix[2][3] = Button14White;
//		botaoMatrix[2][4] = (Button15White;;
        botaoMatrix[3][0] = Button15Red;
        botaoMatrix[3][1] = Button16Red;
        botaoMatrix[3][2] = Button17Red;
        botaoMatrix[3][3] = Button18Red;
        botaoMatrix[3][4] = Button19Red;
        botaoMatrix[4][0] = Button20Red;
        botaoMatrix[4][1] = Button21Red;
        botaoMatrix[4][2] = Button22Red;
        botaoMatrix[4][3] = Button23Red;
        botaoMatrix[4][4] = Button24Red;
//		listaDeBotoes.add(Button25Red);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTabuleiro = new javax.swing.JPanel();
        Button1Blue = new javax.swing.JButton();
        Button2Blue = new javax.swing.JButton();
        Button5Blue = new javax.swing.JButton();
        Button3Blue = new javax.swing.JButton();
        Button4Blue = new javax.swing.JButton();
        Button6Blue = new javax.swing.JButton();
        Button7Blue = new javax.swing.JButton();
        Button8Blue = new javax.swing.JButton();
        Button9Blue = new javax.swing.JButton();
        Button10Blue = new javax.swing.JButton();
        Button11White = new javax.swing.JButton();
        Button12White = new javax.swing.JButton();
        Button13White = new javax.swing.JButton();
        Button14White = new javax.swing.JButton();
        Button15Red = new javax.swing.JButton();
        Button16Red = new javax.swing.JButton();
        Button17Red = new javax.swing.JButton();
        Button18Red = new javax.swing.JButton();
        Button19Red = new javax.swing.JButton();
        Button20Red = new javax.swing.JButton();
        Button21Red = new javax.swing.JButton();
        Button22Red = new javax.swing.JButton();
        Button23Red = new javax.swing.JButton();
        Button24Red = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonEncerrarJogo = new javax.swing.JButton();
        readyButton = new javax.swing.JButton();
        limparTabuleiro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonDebug = new javax.swing.JButton();
        botaoDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTabuleiro.setBackground(new java.awt.Color(128, 185, 24));
        PanelTabuleiro.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));

        Button1Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button1Blue.setToolTipText("");
        Button1Blue.setFocusPainted(false);
        Button1Blue.setName("4-0"); // NOI18N
        Button1Blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1BlueMouseClicked(evt);
            }
        });
        Button1Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1BlueActionPerformed(evt);
            }
        });

        Button2Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button2Blue.setName("4-1"); // NOI18N

        Button5Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button5Blue.setName("4-4"); // NOI18N

        Button3Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button3Blue.setName("4-2"); // NOI18N

        Button4Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button4Blue.setName("4-3"); // NOI18N
        Button4Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4BlueActionPerformed(evt);
            }
        });

        Button6Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button6Blue.setName("3-0"); // NOI18N

        Button7Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button7Blue.setName("3-1"); // NOI18N

        Button8Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button8Blue.setName("3-2"); // NOI18N

        Button9Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button9Blue.setName("3-3"); // NOI18N
        Button9Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9BlueActionPerformed(evt);
            }
        });

        Button10Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button10Blue.setName("3-4"); // NOI18N

        Button11White.setBackground(null);
        Button11White.setName("2-0"); // NOI18N
        Button11White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button11WhiteActionPerformed(evt);
            }
        });

        Button12White.setBackground(null);
        Button12White.setName("10"); // NOI18N
        Button12White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button12WhiteActionPerformed(evt);
            }
        });

        Button13White.setBackground(null);
        Button13White.setName("2-3"); // NOI18N

        Button14White.setBackground(null);
        Button14White.setName("2-4"); // NOI18N

        Button15Red.setBackground(new java.awt.Color(0, 153, 255));
        Button15Red.setName(""); // NOI18N
        Button15Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button15RedActionPerformed(evt);
            }
        });

        Button16Red.setBackground(new java.awt.Color(0, 153, 255));
        Button16Red.setName(""); // NOI18N

        Button17Red.setBackground(new java.awt.Color(0, 153, 255));
        Button17Red.setName(""); // NOI18N
        Button17Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button17RedActionPerformed(evt);
            }
        });

        Button18Red.setBackground(new java.awt.Color(0, 153, 255));
        Button18Red.setName(""); // NOI18N

        Button19Red.setBackground(new java.awt.Color(0, 153, 255));
        Button19Red.setName(""); // NOI18N

        Button20Red.setBackground(new java.awt.Color(0, 153, 255));
        Button20Red.setName(""); // NOI18N
        Button20Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button20RedActionPerformed(evt);
            }
        });

        Button21Red.setBackground(new java.awt.Color(0, 153, 255));
        Button21Red.setName(""); // NOI18N

        Button22Red.setBackground(new java.awt.Color(0, 153, 255));
        Button22Red.setName(""); // NOI18N

        Button23Red.setBackground(new java.awt.Color(0, 153, 255));
        Button23Red.setName(""); // NOI18N

        Button24Red.setBackground(new java.awt.Color(0, 153, 255));
        Button24Red.setName(""); // NOI18N

        javax.swing.GroupLayout PanelTabuleiroLayout = new javax.swing.GroupLayout(PanelTabuleiro);
        PanelTabuleiro.setLayout(PanelTabuleiroLayout);
        PanelTabuleiroLayout.setHorizontalGroup(
            PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabuleiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Button20Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(Button15Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button11White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button6Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button1Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button2Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button7Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button12White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button16Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button21Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button3Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button8Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button17Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button22Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button4Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button9Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button18Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button23Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(Button13White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button5Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button10Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button19Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button24Red, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(Button14White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTabuleiroLayout.setVerticalGroup(
            PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabuleiroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button2Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button6Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button7Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button8Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button9Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button10Blue, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button11White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button12White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button14White, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(Button13White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button17Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button15Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button16Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button18Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button19Red, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button20Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button21Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button22Red, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button23Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button24Red, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("STRATEGY 5x5");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Randomized");

        ButtonEncerrarJogo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonEncerrarJogo.setText("Encerrar Jogo");
        ButtonEncerrarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEncerrarJogoActionPerformed(evt);
            }
        });

        readyButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        readyButton.setText("Ready");
        readyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButtonActionPerformed(evt);
            }
        });

        limparTabuleiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        limparTabuleiro.setText("Clear");
        limparTabuleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTabuleiroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setText("A");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setText("B");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel11.setText("1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setText("2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setText("3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setText("4");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setText("5");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel16.setText("C");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setText("D");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setText("E");

        jButtonDebug.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDebug.setText("Debug");
        jButtonDebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDebugActionPerformed(evt);
            }
        });

        botaoDica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoDica.setText("Dica");
        botaoDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ButtonEncerrarJogo)
                .addGap(147, 147, 147)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoDica)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(readyButton)
                                .addGap(139, 139, 139)
                                .addComponent(jButtonDebug)
                                .addGap(165, 165, 165)
                                .addComponent(limparTabuleiro))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel12)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel13)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel14)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel15)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(botaoDica)
                    .addComponent(ButtonEncerrarJogo))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparTabuleiro)
                            .addComponent(readyButton)
                            .addComponent(jButtonDebug))))
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button1BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1BlueActionPerformed

    }//GEN-LAST:event_Button1BlueActionPerformed

    public JButton getButton(String local) {
        JButton toReturn = new JButton();

        switch (local) {
            case "D1" ->
                toReturn = Button15Red;
            case "D2" ->
                toReturn = Button16Red;
            case "D3" ->
                toReturn = Button17Red;
            case "D4" ->
                toReturn = Button18Red;
            case "D5" ->
                toReturn = Button19Red;
            case "E1" ->
                toReturn = Button20Red;
            case "E2" ->
                toReturn = Button21Red;
            case "E3" ->
                toReturn = Button22Red;
            case "E4" ->
                toReturn = Button23Red;
            case "E5" ->
                toReturn = Button24Red;
        }
        return toReturn;
    }

    public void setButton(String local, Peças peça) {
        JButton botao = getButton(local);
        botao.setName(peça.getPatente());
        botao.setIcon(new ImageIcon(peça.getIcon()));
    }

    private void ButtonEncerrarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEncerrarJogoActionPerformed
        // TODO add your handling code here:
        FinalJogoRandom fjr = new FinalJogoRandom();
        this.dispose();
        fjr.setVisible(true);
    }//GEN-LAST:event_ButtonEncerrarJogoActionPerformed

    private void readyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButtonActionPerformed
//	
        manager.addAction(PanelTabuleiro);
//	addAction(PanelTabuleiro);
        setButtonsToMatrix();
        random.RandomAIPlace(evt, buttonArrayEnemyPC);
        random.MostrarIcones(evt, buttonArrayEnemy, false);
        readyButton.setEnabled(false);
//        random.RandomAIPlace(evt, buttonArray);
    }//GEN-LAST:event_readyButtonActionPerformed

    private void limparTabuleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTabuleiroActionPerformed
        // TODO add your handling code here:
        limparBotoesTabuleiro();
        readyButton.setEnabled(true);
    }//GEN-LAST:event_limparTabuleiroActionPerformed

    private void Button20RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button20RedActionPerformed

    }//GEN-LAST:event_Button20RedActionPerformed

    private void Button4BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4BlueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button4BlueActionPerformed

    private void Button1BlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1BlueMouseClicked

    }//GEN-LAST:event_Button1BlueMouseClicked

    private void Button15RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button15RedActionPerformed
//        Buttom1Red.getBounds();
//        System.out.println(Buttom1Red.getBounds());
//        System.out.println(Buttom1Red.getIcon());
//        System.out.println(Button15Red.getBackground());
    }//GEN-LAST:event_Button15RedActionPerformed

    private void Button12WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button12WhiteActionPerformed
//        jButton12.setIcon(new ImageIcon(this.marechal.getIcon()));
//        setButtonActionListener(jButton12, this.marechal);
    }//GEN-LAST:event_Button12WhiteActionPerformed

    private void Button11WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button11WhiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button11WhiteActionPerformed

    private void Button17RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button17RedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button17RedActionPerformed

    private void Button9BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9BlueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button9BlueActionPerformed

    private void jButtonDebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDebugActionPerformed
        // TODO add your handling code here:
        random.MostrarIcones(evt, buttonArrayEnemy, true);
        jButtonDebug.setEnabled(false);
    }//GEN-LAST:event_jButtonDebugActionPerformed

    private void botaoDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDicaActionPerformed

    }//GEN-LAST:event_botaoDicaActionPerformed

    private void limparBotoesTabuleiro() {
        Button15Red.setIcon(null);
        Button16Red.setIcon(null);
        Button17Red.setIcon(null);
        Button18Red.setIcon(null);
        Button19Red.setIcon(null);
        Button20Red.setIcon(null);
        Button21Red.setIcon(null);
        Button22Red.setIcon(null);
        Button23Red.setIcon(null);
        Button24Red.setIcon(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabuleiroRandom1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabuleiroRandom1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabuleiroRandom1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabuleiroRandom1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabuleiroRandom1().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button10Blue;
    private javax.swing.JButton Button11White;
    private javax.swing.JButton Button12White;
    private javax.swing.JButton Button13White;
    private javax.swing.JButton Button14White;
    private javax.swing.JButton Button15Red;
    private javax.swing.JButton Button16Red;
    private javax.swing.JButton Button17Red;
    private javax.swing.JButton Button18Red;
    private javax.swing.JButton Button19Red;
    private javax.swing.JButton Button1Blue;
    private javax.swing.JButton Button20Red;
    private javax.swing.JButton Button21Red;
    private javax.swing.JButton Button22Red;
    private javax.swing.JButton Button23Red;
    private javax.swing.JButton Button24Red;
    private javax.swing.JButton Button2Blue;
    private javax.swing.JButton Button3Blue;
    private javax.swing.JButton Button4Blue;
    private javax.swing.JButton Button5Blue;
    private javax.swing.JButton Button6Blue;
    private javax.swing.JButton Button7Blue;
    private javax.swing.JButton Button8Blue;
    private javax.swing.JButton Button9Blue;
    private javax.swing.JButton ButtonEncerrarJogo;
    private javax.swing.JPanel PanelTabuleiro;
    private javax.swing.JButton botaoDica;
    private javax.swing.JButton jButtonDebug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limparTabuleiro;
    private javax.swing.JButton readyButton;
    // End of variables declaration//GEN-END:variables
}
