/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gamepoo;

import Pieces.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Xablau
 */
public class TabuleiroSet extends javax.swing.JFrame {

	/**
	 * Creates new form Tabuleiro
	 */
	final JButton[] buttonArrayEnemy = new JButton[10];

	public TabuleiroSet() {
		initComponents();
		setButtonsToMatrix();
		buttonArrayEnemy[0] = Button1Blue;
		buttonArrayEnemy[1] = Button2Blue;
		buttonArrayEnemy[2] = Button3Blue;
		buttonArrayEnemy[3] = Button4Blue;
		buttonArrayEnemy[4] = Button5Blue;
		buttonArrayEnemy[5] = Button6Blue;
		buttonArrayEnemy[6] = Button7Blue;
		buttonArrayEnemy[7] = Button8Blue;
		buttonArrayEnemy[8] = Button9Blue;
		buttonArrayEnemy[9] = Button10Blue;
	}

	private Peças bandeira = new Bandeira();
	private Peças bomba1 = new Bomba();
	private Peças bomba2 = new Bomba();
	private Peças espiao = new Espião();
	private Peças soldado1 = new Soldado();
	private Peças soldado2 = new Soldado();
	private Peças soldado3 = new Soldado();
	private Peças armeiro1 = new Armeiro();
	private Peças armeiro2 = new Armeiro();
	private Peças marechal = new Marechal();
	private boolean secondClickTest = false;
	private JButton botaoAnterior;
	private LinkedList<JButton> listaDeBotoes = new LinkedList<JButton>();
	private JButton[][] botaoMatrix = new JButton[5][5];

	RandomPlacement random = new RandomPlacement();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// + 110 X ------------ + 104 Y
	public void addAction(JPanel panel) {
		Component[] components = PanelTabuleiro.getComponents();
		for (Component component : components) {
			if (component instanceof JButton) {
				JButton button = (JButton) component;
				button.addActionListener(new ActionListener() {
					@Override
					public void actionPerformed(ActionEvent e) {
						if (!secondClickTest) {
							if (button.getIcon() != null && !button.getName().equals("Bomba") && !button.getName().equals("Bandeira")) {
								botaoAnterior = button;
								secondClickTest = true;
								System.out.println(botaoAnterior.getBackground().getRGB());
							}
						} else {
							if (((button.getBounds().x == botaoAnterior.getBounds().x - 110 || botaoAnterior.getBounds().x + 110 == button.getBounds().x) && (button.getBounds().y == botaoAnterior.getBounds().y))
							|| ((button.getBounds().y == botaoAnterior.getBounds().y + 104 || button.getBounds().y == botaoAnterior.getBounds().y - 104) && (button.getBounds().x == botaoAnterior.getBounds().x))) {
								if (button.getIcon() == null && !botaoAnterior.getName().equals("Bomba") && !botaoAnterior.getName().equals("Bandeira")) {
									swapButtons(button, botaoAnterior);
									secondClickTest = false;
								} else if (button.getBackground().getRGB() != botaoAnterior.getBackground().getRGB()){
									combate(botaoAnterior, button);
									secondClickTest = false;
								}
							} else {
								secondClickTest = false;
							}
							secondClickTest = false;
						}
					}
				});
			}
		}
	}
	
	private void setButtonsToMatrix(){
		botaoMatrix[0][0] = Button1Blue;
		botaoMatrix[0][1] = Button2Blue;
		botaoMatrix[0][2] = Button3Blue;
		botaoMatrix[0][3] = Button4Blue;
		botaoMatrix[0][4] = Button5Blue;
		botaoMatrix[1][0] = Button6Blue;
		botaoMatrix[1][1] = Button7Blue;
		botaoMatrix[1][2] = Button8Blue;
		botaoMatrix[1][3] = Button9Blue;
		botaoMatrix[1][4] = Button10Blue;
		botaoMatrix[2][0] = Button11White;
		botaoMatrix[2][1] = Button12White;
		botaoMatrix[2][2] = Button13White;
		botaoMatrix[2][3] = Button14White;
//		botaoMatrix[2][4] = (Button15White;;
		botaoMatrix[3][0] = Button15Red;
		botaoMatrix[3][1] = Button16Red;
		botaoMatrix[3][2] = Button17Red;
		botaoMatrix[3][3] = Button18Red;
		botaoMatrix[3][4] = Button19Red;
		botaoMatrix[4][0] = Button20Red;
		botaoMatrix[4][1] = Button21Red;
		botaoMatrix[4][2] = Button22Red;
		botaoMatrix[4][3] = Button23Red;
		botaoMatrix[4][4] = Button24Red;
//		listaDeBotoes.add(Button25Red);
	}

	public void swapButtons(JButton botao1, JButton botao2) {
		botao1.setIcon(botao2.getIcon());
		botao1.setName(botao2.getName());
		botao1.setBackground(botao2.getBackground());
		clearButton(botao2);
	}

	public void combate(JButton botao1, JButton botao2) {
		int nivel1 = getNivelDaPeça(botao1.getName());
		int nivel2 = getNivelDaPeça(botao2.getName());

		if (nivel1 > nivel2) {
			clearButton(botao2);
		} else if (nivel1 == 3 && nivel2 == 11) {
			clearButton(botao2);
		} else if (nivel1 == 1 && nivel2 == 10) {
			clearButton(botao2);
		} else if (nivel1 == nivel2) {
			clearButton(botao1);
			clearButton(botao2);
		} else {
			clearButton(botao1);
		}
	}

	public int getNivelDaPeça(String nomeDaPeça) {
		int nivel = 0;

		switch (nomeDaPeça) {
			case "Armeiro":
				nivel = armeiro1.getNivel();
				break;
			case "Soldado":
				nivel = soldado1.getNivel();
				break;
			case "Espião":
				nivel = espiao.getNivel();
				break;
			case "Marechal":
				nivel = marechal.getNivel();
				break;
			case "Bomba":
				nivel = bomba1.getNivel();
				break;
			case "Bandeira":
				nivel = bandeira.getNivel();
		}

		return nivel;
	}

	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTabuleiro = new javax.swing.JPanel();
        Button1Blue = new javax.swing.JButton();
        Button2Blue = new javax.swing.JButton();
        Button5Blue = new javax.swing.JButton();
        Button3Blue = new javax.swing.JButton();
        Button4Blue = new javax.swing.JButton();
        Button6Blue = new javax.swing.JButton();
        Button7Blue = new javax.swing.JButton();
        Button8Blue = new javax.swing.JButton();
        Button9Blue = new javax.swing.JButton();
        Button10Blue = new javax.swing.JButton();
        Button11White = new javax.swing.JButton();
        Button12White = new javax.swing.JButton();
        Button13White = new javax.swing.JButton();
        Button14White = new javax.swing.JButton();
        Button15Red = new javax.swing.JButton();
        Button16Red = new javax.swing.JButton();
        Button17Red = new javax.swing.JButton();
        Button18Red = new javax.swing.JButton();
        Button19Red = new javax.swing.JButton();
        Button20Red = new javax.swing.JButton();
        Button21Red = new javax.swing.JButton();
        Button22Red = new javax.swing.JButton();
        Button23Red = new javax.swing.JButton();
        Button24Red = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        readyButton = new javax.swing.JButton();
        limparTabuleiro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        selectionCombos = new javax.swing.JPanel();
        botaoBandeira = new javax.swing.JButton();
        comboBandeira = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        botaoEspiao1s = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboEspiao1s = new javax.swing.JComboBox<>();
        botaoBomba1 = new javax.swing.JButton();
        botaoBomba2 = new javax.swing.JButton();
        comboBomba1 = new javax.swing.JComboBox<>();
        comboBomba2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        botaoSoldado2s1 = new javax.swing.JButton();
        botaoSoldado2s2 = new javax.swing.JButton();
        botaoSoldado2s3 = new javax.swing.JButton();
        botaoDefuse3s1 = new javax.swing.JButton();
        botaoDefuse3s2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboDefuse3s2 = new javax.swing.JComboBox<>();
        comboDefuse3s1 = new javax.swing.JComboBox<>();
        botaoMarechal10 = new javax.swing.JButton();
        comboMarechal10 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboSoldado2s2 = new javax.swing.JComboBox<>();
        comboSoldado2s3 = new javax.swing.JComboBox<>();
        comboSoldado2s1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonDebug = new javax.swing.JButton();
        botaoDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTabuleiro.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));

        Button1Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button1Blue.setToolTipText("");
        Button1Blue.setFocusPainted(false);
        Button1Blue.setName("4-0"); // NOI18N
        Button1Blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1BlueMouseClicked(evt);
            }
        });
        Button1Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1BlueActionPerformed(evt);
            }
        });

        Button2Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button2Blue.setName("4-1"); // NOI18N

        Button5Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button5Blue.setName("4-4"); // NOI18N

        Button3Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button3Blue.setName("4-2"); // NOI18N

        Button4Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button4Blue.setName("4-3"); // NOI18N
        Button4Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4BlueActionPerformed(evt);
            }
        });

        Button6Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button6Blue.setName("3-0"); // NOI18N

        Button7Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button7Blue.setName("3-1"); // NOI18N

        Button8Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button8Blue.setName("3-2"); // NOI18N

        Button9Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button9Blue.setName("3-3"); // NOI18N
        Button9Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9BlueActionPerformed(evt);
            }
        });

        Button10Blue.setBackground(new java.awt.Color(255, 102, 102));
        Button10Blue.setName("3-4"); // NOI18N

        Button11White.setName("2-0"); // NOI18N
        Button11White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button11WhiteActionPerformed(evt);
            }
        });

        Button12White.setName("10"); // NOI18N
        Button12White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button12WhiteActionPerformed(evt);
            }
        });

        Button13White.setName("2-3"); // NOI18N

        Button14White.setName("2-4"); // NOI18N

        Button15Red.setBackground(new java.awt.Color(0, 153, 255));
        Button15Red.setName(""); // NOI18N
        Button15Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button15RedActionPerformed(evt);
            }
        });

        Button16Red.setBackground(new java.awt.Color(0, 153, 255));
        Button16Red.setName(""); // NOI18N

        Button17Red.setBackground(new java.awt.Color(0, 153, 255));
        Button17Red.setName(""); // NOI18N
        Button17Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button17RedActionPerformed(evt);
            }
        });

        Button18Red.setBackground(new java.awt.Color(0, 153, 255));
        Button18Red.setName(""); // NOI18N

        Button19Red.setBackground(new java.awt.Color(0, 153, 255));
        Button19Red.setName(""); // NOI18N

        Button20Red.setBackground(new java.awt.Color(0, 153, 255));
        Button20Red.setName(""); // NOI18N
        Button20Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button20RedActionPerformed(evt);
            }
        });

        Button21Red.setBackground(new java.awt.Color(0, 153, 255));
        Button21Red.setName(""); // NOI18N

        Button22Red.setBackground(new java.awt.Color(0, 153, 255));
        Button22Red.setName(""); // NOI18N

        Button23Red.setBackground(new java.awt.Color(0, 153, 255));
        Button23Red.setName(""); // NOI18N

        Button24Red.setBackground(new java.awt.Color(0, 153, 255));
        Button24Red.setName(""); // NOI18N

        javax.swing.GroupLayout PanelTabuleiroLayout = new javax.swing.GroupLayout(PanelTabuleiro);
        PanelTabuleiro.setLayout(PanelTabuleiroLayout);
        PanelTabuleiroLayout.setHorizontalGroup(
            PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabuleiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Button20Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(Button15Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button11White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button6Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button1Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button2Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button7Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button12White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button16Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button21Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button3Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button8Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button17Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button22Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button4Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button9Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button18Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button23Red, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(Button13White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button5Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button10Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button19Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button24Red, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(Button14White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTabuleiroLayout.setVerticalGroup(
            PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabuleiroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button2Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button6Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button7Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button8Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button9Blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button10Blue, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button11White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button12White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button14White, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(Button13White, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button17Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button15Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button16Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button18Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button19Red, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button20Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button21Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button22Red, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button23Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button24Red, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("STRATEGY 5x5");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Custom");

        jButton26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton26.setText("Return");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        readyButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        readyButton.setText("Ready");
        readyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButtonActionPerformed(evt);
            }
        });

        limparTabuleiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        limparTabuleiro.setText("Clear");
        limparTabuleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTabuleiroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setText("A");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setText("B");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel11.setText("1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setText("2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setText("3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setText("4");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setText("5");

        botaoBandeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bandeira.png"))); // NOI18N
        botaoBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBandeiraActionPerformed(evt);
            }
        });

        comboBandeira.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBandeiraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Bandeira");

        botaoEspiao1s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Espião.png"))); // NOI18N
        botaoEspiao1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEspiao1sActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("1s");

        comboEspiao1s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboEspiao1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspiao1sActionPerformed(evt);
            }
        });

        botaoBomba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bomba.png"))); // NOI18N
        botaoBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBomba1ActionPerformed(evt);
            }
        });

        botaoBomba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bomba.png"))); // NOI18N
        botaoBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBomba2ActionPerformed(evt);
            }
        });

        comboBomba1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBomba1ActionPerformed(evt);
            }
        });

        comboBomba2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBomba2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bombas");

        botaoSoldado2s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Soldado.png"))); // NOI18N
        botaoSoldado2s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSoldado2s1ActionPerformed(evt);
            }
        });

        botaoSoldado2s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Soldado.png"))); // NOI18N
        botaoSoldado2s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSoldado2s2ActionPerformed(evt);
            }
        });

        botaoSoldado2s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Soldado.png"))); // NOI18N
        botaoSoldado2s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSoldado2s3ActionPerformed(evt);
            }
        });

        botaoDefuse3s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Armeiro.png"))); // NOI18N
        botaoDefuse3s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefuse3s1ActionPerformed(evt);
            }
        });

        botaoDefuse3s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Armeiro.png"))); // NOI18N
        botaoDefuse3s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefuse3s2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("2s");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("3s");

        comboDefuse3s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboDefuse3s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDefuse3s2ActionPerformed(evt);
            }
        });

        comboDefuse3s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboDefuse3s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDefuse3s1ActionPerformed(evt);
            }
        });

        botaoMarechal10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marechal.png"))); // NOI18N
        botaoMarechal10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarechal10ActionPerformed(evt);
            }
        });

        comboMarechal10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboMarechal10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarechal10ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("10s");

        comboSoldado2s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboSoldado2s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSoldado2s2ActionPerformed(evt);
            }
        });

        comboSoldado2s3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboSoldado2s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSoldado2s3ActionPerformed(evt);
            }
        });

        comboSoldado2s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "D1", "D2", "D3", "D4", "D5", "E1", "E2", "E3", "E4", "E5" }));
        comboSoldado2s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSoldado2s1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectionCombosLayout = new javax.swing.GroupLayout(selectionCombos);
        selectionCombos.setLayout(selectionCombosLayout);
        selectionCombosLayout.setHorizontalGroup(
            selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionCombosLayout.createSequentialGroup()
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoDefuse3s1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBomba1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoBandeira))
                            .addComponent(comboBandeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDefuse3s1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(selectionCombosLayout.createSequentialGroup()
                                        .addComponent(comboSoldado2s2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(comboSoldado2s1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(selectionCombosLayout.createSequentialGroup()
                                        .addComponent(botaoSoldado2s2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoSoldado2s1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionCombosLayout.createSequentialGroup()
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSoldado2s3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(selectionCombosLayout.createSequentialGroup()
                                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoBomba2)
                                    .addComponent(comboBomba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botaoDefuse3s2)
                                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comboMarechal10, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                            .addComponent(botaoMarechal10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboDefuse3s2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(comboEspiao1s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoEspiao1s))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(53, 53, 53))
                    .addGroup(selectionCombosLayout.createSequentialGroup()
                        .addComponent(botaoSoldado2s3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        selectionCombosLayout.setVerticalGroup(
            selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionCombosLayout.createSequentialGroup()
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botaoBandeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoEspiao1s))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEspiao1s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botaoBomba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoBomba1))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBomba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoSoldado2s1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSoldado2s2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6)
                    .addComponent(botaoSoldado2s3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectionCombosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoDefuse3s2))
                    .addGroup(selectionCombosLayout.createSequentialGroup()
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboSoldado2s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboSoldado2s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(selectionCombosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(comboSoldado2s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoDefuse3s1)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDefuse3s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDefuse3s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(selectionCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoMarechal10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMarechal10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel16.setText("C");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setText("D");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setText("E");

        jButtonDebug.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDebug.setText("Debug");
        jButtonDebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDebugActionPerformed(evt);
            }
        });

        botaoDica.setText("Dica");
        botaoDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel12)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel13)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel14)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(readyButton)
                                .addGap(139, 139, 139)
                                .addComponent(jButtonDebug)
                                .addGap(165, 165, 165)
                                .addComponent(limparTabuleiro)))))
                .addGap(18, 18, 18)
                .addComponent(selectionCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton26)
                .addGap(306, 306, 306)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoDica)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(botaoDica))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel9)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel16)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel17)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(limparTabuleiro)
                                    .addComponent(readyButton)
                                    .addComponent(jButtonDebug))))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectionCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button1BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1BlueActionPerformed

    }//GEN-LAST:event_Button1BlueActionPerformed

	public JButton getButton(String local) {
		JButton toReturn = new JButton();

		switch (local) {
			case "D1" ->
				toReturn = Button15Red;
			case "D2" ->
				toReturn = Button16Red;
			case "D3" ->
				toReturn = Button17Red;
			case "D4" ->
				toReturn = Button18Red;
			case "D5" ->
				toReturn = Button19Red;
			case "E1" ->
				toReturn = Button20Red;
			case "E2" ->
				toReturn = Button21Red;
			case "E3" ->
				toReturn = Button22Red;
			case "E4" ->
				toReturn = Button23Red;
			case "E5" ->
				toReturn = Button24Red;
		}
		return toReturn;
	}

	public void setButton(String local, Peças peça) {
		JButton botao = getButton(local);
		botao.setName(peça.getPatente());
		botao.setIcon(new ImageIcon(peça.getIcon()));
	}

	private void clearButton(JButton botao) {
		botao.setIcon(null);
		botao.setName(null);
		botao.setBackground(null);
	}

	private void removeItens(JComboBox fonte) {
		Component[] components = selectionCombos.getComponents();
		for (Component component : components) {
			if (component instanceof JComboBox) {
				JComboBox comboBox = (JComboBox) component;
				if (!comboBox.equals(fonte)) {
					comboBox.removeItem(fonte.getSelectedItem().toString());
				}
			}
		}
	}

	private void adicionarItens(JComboBox fonte) {
		Component[] components = selectionCombos.getComponents();
		for (Component component : components) {
			if (component instanceof JComboBox) {
				JComboBox comboBox = (JComboBox) component;
				if (!comboBox.equals(fonte)) {
					comboBox.addItem(fonte.getSelectedItem().toString());
				}
			}
		}
	}

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
		// TODO add your handling code here:
		Menu m = new Menu();
		this.dispose();
		m.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void readyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButtonActionPerformed
		addAction(PanelTabuleiro);
		setButtonsToMatrix();
		limparTabuleiro.setEnabled(false);
		random.RandomAIPlace(evt, buttonArrayEnemy);
		random.MostrarIcones(evt, buttonArrayEnemy, false);
//        random.RandomAIPlace(evt, buttonArray);
    }//GEN-LAST:event_readyButtonActionPerformed

    private void limparTabuleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTabuleiroActionPerformed
		// TODO add your handling code here:
		limparBotoesTabuleiro();
		refazerBotoes();
		adicionarItens(comboBandeira);
		adicionarItens(comboBomba1);
		adicionarItens(comboBomba2);
		adicionarItens(comboDefuse3s1);
		adicionarItens(comboDefuse3s2);
		adicionarItens(comboEspiao1s);
		adicionarItens(comboMarechal10);
		adicionarItens(comboSoldado2s1);
		adicionarItens(comboSoldado2s2);
		adicionarItens(comboSoldado2s3);
    }//GEN-LAST:event_limparTabuleiroActionPerformed

    private void Button20RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button20RedActionPerformed

    }//GEN-LAST:event_Button20RedActionPerformed

    private void comboSoldado2s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSoldado2s1ActionPerformed
		if (!comboSoldado2s1.getSelectedItem().toString().equals("Select")) {
			setButton(comboSoldado2s1.getSelectedItem().toString(), this.soldado1);
//        setButtonActionListener(getButton(comboSoldado2s1.getSelectedItem().toString()), this.soldado1);
			comboSoldado2s1.setEnabled(false);
			botaoSoldado2s1.setEnabled(false);
			setName("Soldado2s1");
			removeItens(comboSoldado2s1);
		}
    }//GEN-LAST:event_comboSoldado2s1ActionPerformed

    private void comboSoldado2s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSoldado2s3ActionPerformed
		// TODO add your handling code here:
		if (!comboSoldado2s3.getSelectedItem().toString().equals("Select")) {
			setButton(comboSoldado2s3.getSelectedItem().toString(), this.soldado3);
//        setButtonActionListener(getButton(comboSoldado2s3.getSelectedItem().toString()), this.soldado3);
			comboSoldado2s3.setEnabled(false);
			botaoSoldado2s3.setEnabled(false);
			setName("Soldado2s3");
			removeItens(comboSoldado2s3);
		}
    }//GEN-LAST:event_comboSoldado2s3ActionPerformed

    private void comboSoldado2s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSoldado2s2ActionPerformed
		// TODO add your handling code here:
		if (!comboSoldado2s2.getSelectedItem().toString().equals("Select")) {
			setButton(comboSoldado2s2.getSelectedItem().toString(), this.soldado2);
//        setButtonActionListener(getButton(comboSoldado2s2.getSelectedItem().toString()), this.soldado2);
//        setPeçaToBotao(getButton(comboSoldado2s2.getSelectedItem().toString()), this.soldado2);;
			comboSoldado2s2.setEnabled(false);
			botaoSoldado2s2.setEnabled(false);
			setName("Soldado2s2");
			removeItens(comboSoldado2s2);
		}
    }//GEN-LAST:event_comboSoldado2s2ActionPerformed

    private void comboMarechal10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarechal10ActionPerformed
		if (!comboMarechal10.getSelectedItem().toString().equals("Select")) {
			setButton(comboMarechal10.getSelectedItem().toString(), this.marechal);
//        setButtonActionListener(getButton(comboMarechal10.getSelectedItem().toString()), this.marechal);
			comboMarechal10.setEnabled(false);
			botaoMarechal10.setEnabled(false);
			setName("Marechal");
			removeItens(comboMarechal10);
		}
    }//GEN-LAST:event_comboMarechal10ActionPerformed

    private void botaoMarechal10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarechal10ActionPerformed
		// TODO add your handling code here:
		comboMarechal10.setEnabled(true);
    }//GEN-LAST:event_botaoMarechal10ActionPerformed

    private void comboDefuse3s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDefuse3s1ActionPerformed
		if (!comboDefuse3s1.getSelectedItem().toString().equals("Select")) {
			setButton(comboDefuse3s1.getSelectedItem().toString(), this.armeiro1);
//        setButtonActionListener(getButton(comboDefuse3s1.getSelectedItem().toString()), this.armeiro1);
			comboDefuse3s1.setEnabled(false);
			botaoDefuse3s1.setEnabled(false);
			setName("Defuse3s1");
			removeItens(comboDefuse3s1);
		}
    }//GEN-LAST:event_comboDefuse3s1ActionPerformed

    private void comboDefuse3s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDefuse3s2ActionPerformed
		// TODO add your handling code here:
		if (!comboDefuse3s2.getSelectedItem().toString().equals("Select")) {
			setButton(comboDefuse3s2.getSelectedItem().toString(), this.armeiro2);
//        setButtonActionListener(getButton(comboDefuse3s2.getSelectedItem().toString()), this.armeiro2);
			comboDefuse3s2.setEnabled(false);
			botaoDefuse3s2.setEnabled(false);
			setName("Defuse3s2");
			removeItens(comboDefuse3s2);
		}
    }//GEN-LAST:event_comboDefuse3s2ActionPerformed

    private void botaoDefuse3s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefuse3s2ActionPerformed
		// TODO add your handling code here:
		comboDefuse3s2.setEnabled(true);
    }//GEN-LAST:event_botaoDefuse3s2ActionPerformed

    private void botaoDefuse3s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefuse3s1ActionPerformed
		// TODO add your handling code here:
		comboDefuse3s1.setEnabled(true);
    }//GEN-LAST:event_botaoDefuse3s1ActionPerformed

    private void botaoSoldado2s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSoldado2s3ActionPerformed
		// TODO add your handling code here:
		comboSoldado2s3.setEnabled(true);
    }//GEN-LAST:event_botaoSoldado2s3ActionPerformed

    private void botaoSoldado2s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSoldado2s2ActionPerformed
		// TODO add your handling code here:
		comboSoldado2s2.setEnabled(true);
    }//GEN-LAST:event_botaoSoldado2s2ActionPerformed

    private void botaoSoldado2s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSoldado2s1ActionPerformed
		// TODO add your handling code here:
		comboSoldado2s1.setEnabled(true);
    }//GEN-LAST:event_botaoSoldado2s1ActionPerformed

    private void comboBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBomba2ActionPerformed
		// TODO add your handling code here:
		if (!comboBomba2.getSelectedItem().toString().equals("Select")) {
			setButton(comboBomba2.getSelectedItem().toString(), this.bomba2);
//        setButtonActionListener(getButton(comboBomba2.getSelectedItem().toString()), this.bomba2);
			comboBomba2.setEnabled(false);
			botaoBomba2.setEnabled(false);
			setName("Bomba2");
			removeItens(comboBomba2);
		}
    }//GEN-LAST:event_comboBomba2ActionPerformed

    private void comboBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBomba1ActionPerformed
		if (!comboBomba1.getSelectedItem().toString().equals("Select")) {
			setButton(comboBomba1.getSelectedItem().toString(), this.bomba1);
//        setButtonActionListener(getButton(comboBomba1.getSelectedItem().toString()), this.bomba1);
			comboBomba1.setEnabled(false);
			botaoBomba1.setEnabled(false);
			setName("Bomba1");
			removeItens(comboBomba1);
		}
    }//GEN-LAST:event_comboBomba1ActionPerformed

    private void botaoBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBomba2ActionPerformed
		// TODO add your handling code here:
		comboBomba2.setEnabled(true);
    }//GEN-LAST:event_botaoBomba2ActionPerformed

    private void botaoBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBomba1ActionPerformed
		// TODO add your handling code here:
		comboBomba1.setEnabled(true);
    }//GEN-LAST:event_botaoBomba1ActionPerformed

    private void comboEspiao1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspiao1sActionPerformed
		if (!comboEspiao1s.getSelectedItem().toString().equals("Select")) {
			setButton(comboEspiao1s.getSelectedItem().toString(), this.espiao);
//        setButtonActionListener(getButton(comboEspiao1s.getSelectedItem().toString()), this.espiao);
			comboEspiao1s.setEnabled(false);
			botaoEspiao1s.setEnabled(false);
			setName("Espiao");
			removeItens(comboEspiao1s);
		}
    }//GEN-LAST:event_comboEspiao1sActionPerformed

    private void botaoEspiao1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEspiao1sActionPerformed
		// TODO add your handling code here:
		comboEspiao1s.setEnabled(true);
    }//GEN-LAST:event_botaoEspiao1sActionPerformed

    private void comboBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBandeiraActionPerformed
		// TODO add your handling code here:
		if (!comboBandeira.getSelectedItem().toString().equals("Select")) {
			setButton(comboBandeira.getSelectedItem().toString(), this.bandeira);
//        setButtonActionListener(getButton(comboBandeira.getSelectedItem().toString()), this.bandeira);
			comboBandeira.setEnabled(false);
			botaoBandeira.setEnabled(false);
			setName("Bandeira");
			removeItens(comboBandeira);
		}
    }//GEN-LAST:event_comboBandeiraActionPerformed

    private void botaoBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBandeiraActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_botaoBandeiraActionPerformed

    private void Button4BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4BlueActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_Button4BlueActionPerformed

    private void Button1BlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1BlueMouseClicked

    }//GEN-LAST:event_Button1BlueMouseClicked

    private void Button15RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button15RedActionPerformed
//        Buttom1Red.getBounds();
//        System.out.println(Buttom1Red.getBounds());
//        System.out.println(Buttom1Red.getIcon());
//        System.out.println(Button15Red.getBackground());
    }//GEN-LAST:event_Button15RedActionPerformed

    private void Button12WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button12WhiteActionPerformed
//        jButton12.setIcon(new ImageIcon(this.marechal.getIcon()));
//        setButtonActionListener(jButton12, this.marechal);
    }//GEN-LAST:event_Button12WhiteActionPerformed

    private void Button11WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button11WhiteActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_Button11WhiteActionPerformed

    private void Button17RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button17RedActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_Button17RedActionPerformed

    private void Button9BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9BlueActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_Button9BlueActionPerformed

    private void jButtonDebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDebugActionPerformed
		// TODO add your handling code here:
		random.MostrarIcones(evt, buttonArrayEnemy, true);
		jButtonDebug.setEnabled(false);
    }//GEN-LAST:event_jButtonDebugActionPerformed

    private void botaoDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDicaActionPerformed

    }//GEN-LAST:event_botaoDicaActionPerformed

	private void refazerBotoes() {
		comboBandeira.setEnabled(true);
		comboEspiao1s.setEnabled(true);
		comboBomba1.setEnabled(true);
		comboBomba2.setEnabled(true);
		comboSoldado2s1.setEnabled(true);
		comboSoldado2s2.setEnabled(true);
		comboSoldado2s3.setEnabled(true);
		comboDefuse3s1.setEnabled(true);
		comboDefuse3s2.setEnabled(true);
		comboMarechal10.setEnabled(true);
		botaoBandeira.setEnabled(true);
		botaoEspiao1s.setEnabled(true);
		botaoBomba1.setEnabled(true);
		botaoBomba2.setEnabled(true);
		botaoSoldado2s1.setEnabled(true);
		botaoSoldado2s2.setEnabled(true);
		botaoSoldado2s3.setEnabled(true);
		botaoDefuse3s1.setEnabled(true);
		botaoDefuse3s2.setEnabled(true);
		botaoMarechal10.setEnabled(true);
	}

	private void limparBotoesTabuleiro() {
		Button15Red.setIcon(null);
		Button16Red.setIcon(null);
		Button17Red.setIcon(null);
		Button18Red.setIcon(null);
		Button19Red.setIcon(null);
		Button20Red.setIcon(null);
		Button21Red.setIcon(null);
		Button22Red.setIcon(null);
		Button23Red.setIcon(null);
		Button24Red.setIcon(null);
	}

	private void refazerCombos() {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TabuleiroSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TabuleiroSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TabuleiroSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TabuleiroSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TabuleiroSet().setVisible(true);
			}
		});

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button10Blue;
    private javax.swing.JButton Button11White;
    private javax.swing.JButton Button12White;
    private javax.swing.JButton Button13White;
    private javax.swing.JButton Button14White;
    private javax.swing.JButton Button15Red;
    private javax.swing.JButton Button16Red;
    private javax.swing.JButton Button17Red;
    private javax.swing.JButton Button18Red;
    private javax.swing.JButton Button19Red;
    private javax.swing.JButton Button1Blue;
    private javax.swing.JButton Button20Red;
    private javax.swing.JButton Button21Red;
    private javax.swing.JButton Button22Red;
    private javax.swing.JButton Button23Red;
    private javax.swing.JButton Button24Red;
    private javax.swing.JButton Button2Blue;
    private javax.swing.JButton Button3Blue;
    private javax.swing.JButton Button4Blue;
    private javax.swing.JButton Button5Blue;
    private javax.swing.JButton Button6Blue;
    private javax.swing.JButton Button7Blue;
    private javax.swing.JButton Button8Blue;
    private javax.swing.JButton Button9Blue;
    private javax.swing.JPanel PanelTabuleiro;
    private javax.swing.JButton botaoBandeira;
    private javax.swing.JButton botaoBomba1;
    private javax.swing.JButton botaoBomba2;
    private javax.swing.JButton botaoDefuse3s1;
    private javax.swing.JButton botaoDefuse3s2;
    private javax.swing.JButton botaoDica;
    private javax.swing.JButton botaoEspiao1s;
    private javax.swing.JButton botaoMarechal10;
    private javax.swing.JButton botaoSoldado2s1;
    private javax.swing.JButton botaoSoldado2s2;
    private javax.swing.JButton botaoSoldado2s3;
    private javax.swing.JComboBox<String> comboBandeira;
    private javax.swing.JComboBox<String> comboBomba1;
    private javax.swing.JComboBox<String> comboBomba2;
    private javax.swing.JComboBox<String> comboDefuse3s1;
    private javax.swing.JComboBox<String> comboDefuse3s2;
    private javax.swing.JComboBox<String> comboEspiao1s;
    private javax.swing.JComboBox<String> comboMarechal10;
    private javax.swing.JComboBox<String> comboSoldado2s1;
    private javax.swing.JComboBox<String> comboSoldado2s2;
    private javax.swing.JComboBox<String> comboSoldado2s3;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButtonDebug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limparTabuleiro;
    private javax.swing.JButton readyButton;
    private javax.swing.JPanel selectionCombos;
    // End of variables declaration//GEN-END:variables
}
